'use client'
import { Provider } from '@/components/context/MyContext'
import '../../styles/globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='px-[120px]'>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
